### ISSUE TITLE
grunt-concurrent does not recognize generated config

### ISSUE THREAD

**Issue by illepic** [sindresorhus/grunt-concurrent#72] opened 2015-08-13 18:56 UTC
Grunt plugins like [usemin](https://github.com/yeoman/grunt-usemin) generate tasks on the fly based off of parsing project files. 

grunt-concurrent does not recognize these newly generated tasks. For instance, usemin generates three tasks: concat:generated, cssmin:generated, uglify:generated which can be referenced from any regular main `grunt.registerTask` but not from within

    // Fails with: Verifying property cssmin.generated exists in config...ERROR
    concurrent: {
      'build': [
        'cssmin:generated',
        'uglify:generated'
      ]
    }

**Comment by sindresorhus** [comment] 2015-08-13 18:59
Pretty much a duplicate of https://github.com/sindresorhus/grunt-concurrent/issues/54. Not possible for grunt-concurrent to get dynamic config as each task is spawned in separate grunt child processes and they don't share any context.

**Closed by sindresorhus** 2015-08-13 18:59 UTC

**Comment by illepic** [comment] 2015-08-13 19:08
Cheers, thanks!
