### ISSUE TITLE
Setting task options doesn't works

### ISSUE THREAD

**Issue by Invis1ble** [sindresorhus/grunt-concurrent#60] opened 2015-06-23 05:16 UTC
Hello. I have `concat` task in my `Gruntfile.js` and I set its options dynamically:
```javascript
    grunt.initConfig({
        concurrent: {
            // some tasks
            build: [
                // some subtasks
                'concat:frontofficeCommonScripts'
            ]
        },
        concat: {
            frontofficeCommonScripts: {
                src: [
                    // some files
                ],
                dest: someDest
            },
            // some other subtasks
        },
        // some other tasks
    });

    grunt.registerTask('development', function () {
        grunt.config.set('concat.options.sourceMap', true);

        grunt.task.run(
            // some tasks
            'concurrent:build'
        );
    });
```
When I trying to run `development` task source map is not created, also `--verbose` shows during building:

> Options: separator="\n", banner="", footer="", stripBanners=false, process=false, sourceMap=false, sourceMapName=undefined, sourceMapStyle="embed"

Same `development` task runned without `concurrent` creates source map fine.
How can I fix this or it is a bug?

**Comment by sindresorhus** [comment] 2015-06-23 10:28
Duplicate of #54.

**Closed by sindresorhus** 2015-06-23 10:28 UTC
